Increment3
v1tbrah/metricsAndAlerting pull request #9
Opened 2022-07-13 20:23 UTC by v1tbrah

2022-07-14 07:56 UTC, bambruysk requested changes
Самое важное - это нужно вывести хранение метрик в отдельные слои и структуры. Ну и код хендлеров так же можно упростить. 
Также - если у нас что-то экспортируется то это нужно прокомментировать.
И конечно очень важно логгирование. Нужно добавить

2022-07-14 07:56 UTC, bambruysk commented on internal/agent/agent.go
> +	"github.com/go-resty/resty/v2"
Лучше упорядочить импорты https://practicum-students.slack.com/archives/C03M8QT91D1/p1657701050055759

2022-07-14 07:56 UTC, bambruysk commented on internal/agent/agent.go
> +const (
Для лучшей тестируемости и гибкости эти параметры лучше объединить в структуру Options и привязать ее экземплар к агенту

2022-07-14 07:56 UTC, bambruysk commented on internal/agent/agent.go
> +	go func() {
Эти горутины завершатся когда придет сигнал завершения?

2022-07-14 07:56 UTC, bambruysk commented on internal/agent/agent.go
> +	infoM, err1 := a.metrics.Info(nameM)
почему разные ошибки? Мне кажется можно обойтись одной

2022-07-14 07:56 UTC, bambruysk commented on internal/agent/metric/metric.go
> +type Metrics struct {
Эта структура читается и обновляется из разных горутин, для лушчей надежности хорошо бы обложить ее мьютексами

2022-07-14 07:56 UTC, bambruysk commented on internal/server/api/metric/metric.go
> +	gauge   map[string]string
Эти мапы нужно вытащить в отдельный слой, так как api не должен отвечать за хранение данных. К тому же они непотокобезопасны и доступ к ним лучше защитить

2022-07-14 07:56 UTC, bambruysk commented on internal/server/handler/handler.go
> +var validUpdateHandlers = map[string]func(metric *metric.Metrics, infoM *metric.Info, w http.ResponseWriter, r *http.Request){
достаточно сложная конструкцция, в чем ее задумка?

2022-07-14 07:56 UTC, bambruysk commented on internal/server/handler/handler_test.go
> +	var metricWithAlloc = metric.NewMetrics()
тест зависит от реализации других пакетов. Это не хорошо, лучше бы замокать метрики

2022-07-14 07:56 UTC, bambruysk commented on internal/server/handler/handler_test.go
> +			name: "Test Update /update/counter/PollCount/1.0 Bad Request (invalid value)",
Много тесткейсов - это очень хорошо

2022-07-14 07:56 UTC, bambruysk commented on internal/server/api/api.go
> +	r.Post("/update/{type}/{metric}/{val}", handler.UpdateHandler(m))
хендлеры мргут быть методами и ссылаться на поля своей структуры , не стоитпередавать им какие-то параметры. Создавая хендлеры на лету, это усложняет код и делает его более трудным в сопровождении и изменении

2022-07-14 07:56 UTC, bambruysk commented on internal/server/page/page.go
> +package page
Безусловно интересная фича, выводить страничку с метрики на запущенном сервере. +

2022-07-14 18:48 UTC, v1tbrah commented on internal/agent/agent.go
> +	go func() {
Насколько я понимаю, завершатся. Почему? - Потому-что сразу за считыванием сигнала завершения идет строчка os.Exit(0), а она, согласно официальной документации, завершает выполнение программы (даже defer() не выполняются). Если завершается программа, значит завершается рутина main(), если завершается рутина main(), значит завершаются все дочерние рутины.

2022-07-14 22:20 UTC, v1tbrah commented on internal/server/page/page.go
> +package page
это требование по заданию)

2022-07-14 22:22 UTC, v1tbrah commented on internal/server/api/api.go
> +	r.Post("/update/{type}/{metric}/{val}", handler.UpdateHandler(m))
переделал

2022-07-14 22:28 UTC, v1tbrah commented on internal/server/handler/handler_test.go
> +	var metricWithAlloc = metric.NewMetrics()
Вот тут я совсем не понимаю как это сделать... Тем более, что хендлер теперь будет методом API, а апи при создании конструктором вызывает конструктор метрик. Можете привести пример?

2022-07-14 22:30 UTC, v1tbrah commented on internal/server/handler/handler.go
> +var validUpdateHandlers = map[string]func(metric *metric.Metrics, infoM *metric.Info, w http.ResponseWriter, r *http.Request){
Задумка была в том, чтобы не писать Если ТипМетрики = "gauge" Тогда верни ПервыйХендлер, иначе верни ВторойХендлер. Согласен, некрасиво, переделал.

2022-07-14 22:30 UTC, v1tbrah commented on internal/server/api/metric/metric.go
> +	gauge   map[string]string
сделано

2022-07-14 22:30 UTC, v1tbrah commented on internal/agent/metric/metric.go
> +type Metrics struct {
сделано

2022-07-14 22:30 UTC, v1tbrah commented on internal/agent/agent.go
> +	infoM, err1 := a.metrics.Info(nameM)
да, поправил

2022-07-14 22:31 UTC, v1tbrah commented on internal/agent/agent.go
> +const (
сделано

2022-07-14 22:32 UTC, v1tbrah commented on internal/agent/agent.go
> +	"github.com/go-resty/resty/v2"
сделано

2022-07-15 20:25 UTC, v1tbrah commented on internal/server/api/metric/metric.go
> +	gauge   map[string]string
сделано

2022-07-17 08:06 UTC, bambruysk commented on internal/agent/agent.go
> +	go func() {
Graceful shutdown  у нас сейчас не требуется, и это не относится к сдаче работы. Но основная идея этого подхода - немного задержаться с выходом и успеть завершиться штатно.  То есть чтобы отработали как раз все закрытия, defer и прочее. Например, сервер успеет обработать входящие запросы ( хотя бы что-то ответить, чтобы соединение не висело) Поэтому горутины слушают канал закрытия,  контексты и прочее.

2022-07-17 08:10 UTC, bambruysk commented on internal/server/page/page.go
> +package page
Да, просто без нее тесты тоже проходят) И не все это делают

2022-07-17 09:08 UTC, bambruysk commented on internal/server/handler/handler_test.go
> +	var metricWithAlloc = metric.NewMetrics()
api можно не создавать конструктором в тестах,  а сразу создать структуру с  нужными полями.  Дальше используем пакет testify/mock - https://blog.lamida.org/mocking-in-golang-using-testify/  например так. Проще говоря мы подменяем все методы структуры реальной ( тут конечно удобнее интерфейсы) структурой моковой  и тест работает так как нам нужно, Кроме т ого это позволяет например проверить что будет если методы начнут возвращать ошибки или нестандартные значения

2022-07-19 08:19 UTC, bambruysk commented
можно сливать

2022-07-19 08:20 UTC, bambruysk approved these changes

2022-07-23 15:42 UTC, merged